### PR TITLE
Track lowest inbound channel fees per channel direction

### LINKED ISSUE #1686: `remove_channel_in_nodes` (and `channel_failed` with `!is_permanent`) don't update `lowest_inbound_channel_fees`
While both of these shouldn't cause incorrect routing behavior, they may result in the `lowest_inboud_channel_fees` value being spuriously high, which could cause slower than optimal routing.

I don't think the right solution here is to just fix the behavior in question, though, I think we really should revisit the `lowest_inbound_channel_fees` behavior entirely - when I last benchmarked the difference between A* and dijkstra's performance on our router A* was a good bit faster, but our router has changed a *lot* since then, and I think there's a good chance A* isn't faster anymore (it does imply an extra map lookup during routing!). Before we yank it out entirely, though, I think we should look into storing the `lowest_inbound_channel_fees` field in the per-channel data as well, avoiding the extra map lookup, which may leave A* a lot faster still.

### PR DESCRIPTION
**Pull request by naumenkogs**
This allows to avoid iterating through the nodes data to see what would be the cost to reach a given node while routing.

Closes #1686.

### CODE REVIEW

**Comment by tnull** [comment]
> Given that, I'm wondering if we should just rip out all the A* stuff and go full-dijkstras.

Hum, IIUC going back to a Dijkstra could generally simplify things quite a bit. So primarily spoken from a maintainability perspective, this might be a good idea, if there's not a massive performance difference anymore. Also, I started playing around a bit with replacing the macros with inlined methods in an experimental branch a while back, which might get quite a bit easier by switching back. I think if we decide to switch back I'd like to give this another go and see what the benchmarks say.

**Comment by naumenkogs** [comment]
@TheBlueMatt I'm not sure I understand what you're saying 100% so I'll try to rephrase and please correct me if I'm wrong.

My code hasn't improved the performance of A* (even made a little worse), although we replaced an expensive map call with trivial in-memory field access.

I think one reason could be the other part we updated (keeping up-to-date data). So perhaps drop *newly added* `recompute_and_update_lowest_inbound_channel_fees` calls and compare? If this would make more sense, it would mean that my PR simply increased the routing quality while keeping performance the same. But that's probably not that important in the end, when we compare to Dijkstra (see below).

---------------------

Are you implying because zero-fee channels are so common A* is bad at optimizing, and performs similarly to Dijkstra?

I don't see a good way to check this theory (perhaps `if fee==zero skip`?), but since the numbers speak for themselves, I probably agree to switch full-Dijkstra for the current network.

**Comment by naumenkogs** [comment]
So practically speaking, unless someone shows up and gives us new evidence/idea, we should close this PR/issue and bring back Dijkstra instead, i guess.

**Comment by naumenkogs** [comment]
I guess once #1724 is merged, we can use that code for routing payments unless some new good news about A* emerge.

**Pull request closed without merging**
