### PR TITLE
Use `ChainHash` instead of `BlockHash` as applicable

### PR DESCRIPTION
**Pull request by jkczyz**
`ChainHash` is more appropriate for places where an arbitrary `BlockHash` is not desirable. This type was introduced in later versions of the `bitcoin` crate, thus `BlockHash` was used instead.

Using `ChainHash` also makes it easier to check if `ChannelManager` is compatible with an `Offer`.

### CODE REVIEW

**Comment by jkczyz** [comment]
@TheBlueMatt I'm at a loss as to why the full stack fuzz test uses a seemingly incorrect chain hash of `0000000000000000000000000000000000000000000000000000000000000075`:

https://github.com/lightningdevkit/rust-lightning/blob/2c51080449d647339b3a1ef80e386e8cc7b59fae/fuzz/src/full_stack.rs#L775

But when initializing `ChannelManager` with `Network::Bitcoin`, the `genesis_hash` is indeed that when examining with `dbg!`.

https://github.com/lightningdevkit/rust-lightning/blob/2c51080449d647339b3a1ef80e386e8cc7b59fae/fuzz/src/full_stack.rs#L459-L464

https://github.com/lightningdevkit/rust-lightning/blob/2c51080449d647339b3a1ef80e386e8cc7b59fae/lightning/src/ln/channelmanager.rs#L2261

However, it is the expected `6fe28c0ab6f1b372c1a6a246ae63f74f931e8365e15a089c68d6190000000000` in normal tests. Is there something about the fuzz testing setup that gives a different block hash for the genesis block? While debugging, the merkle root looks glaringly wrong as `000000000000000000000000000000000000000000000000000000000000001b`.

```
[/Users/jkczyz/src/rust-lightning/lightning/src/ln/channelmanager.rs:2261] params.network = Bitcoin
[/Users/jkczyz/src/rust-lightning/lightning/src/ln/channelmanager.rs:2261] genesis_block(dbg!(params.network)) = Block {
    header: BlockHeader {
        version: 1,
        prev_blockhash: 0000000000000000000000000000000000000000000000000000000000000000,
        merkle_root: 000000000000000000000000000000000000000000000000000000000000001b,
        time: 1231006505,
        bits: 486604799,
        nonce: 2083236893,
    },
    txdata: [
        Transaction {
            version: 1,
            lock_time: PackedLockTime(
                0,
            ),
            input: [
                TxIn {
                    previous_output: OutPoint {
                        txid: 0000000000000000000000000000000000000000000000000000000000000000,
                        vout: 4294967295,
                    },
                    script_sig: Script(OP_PUSHBYTES_4 ffff001d OP_PUSHBYTES_1 04 OP_PUSHBYTES_69 5468652054696d65732030332f4a616e2f32303039204368616e63656c6c6f72206f6e206272696e6b206f66207365636f6e64206261696c6f757420666f722062616e6b73),
                    sequence: Sequence(
                        4294967295,
                    ),
                    witness: Witness {
                        content: [],
                        witness_elements: 0,
                        last: 0,
                        second_to_last: 0,
                    },
                },
            ],
            output: [
                TxOut {
                    value: 5000000000,
                    script_pubkey: Script(OP_PUSHBYTES_65 04678afdb0fe5548271967f1a67130b7105cd6a828e03909a67962e0ea1f61deb649f6bc3f4cef38c4f35504e51ec112de5c384df7ba0b8d578a4c702b6bf11d5f OP_CHECKSIG),
                },
            ],
        },
    ],
}
[/Users/jkczyz/src/rust-lightning/lightning/src/ln/channelmanager.rs:2261] dbg!(genesis_block(dbg! (params.network))).header.block_hash() = 0000000000000000000000000000000000000000000000000000000000000075
```

**Comment by jkczyz** [comment]
Ah, thanks! Should be working now.

**Comment by valentinewallace** [comment]
LGTM after CI fix.

**Comment by jkczyz** [comment]
Rebased

**Review by dunxen — APPROVED** [review]

**Review by valentinewallace — APPROVED** [review]

**Pull request merged**
