### PR TITLE
Allow configuring different max fee rate from peer

### PR DESCRIPTION
**Pull request by benthecarman**
We've run into issues a few times where channels will get force closed because CLN's fee estimator isn't as good as ours so the fee rate will be too high, resulting in a force close. It'd be nice if we'd have the ability to be able to increase this limit because generally this isn't malicious, just different views of the mempool.

Alternatively would be nice if we can have an option to just deactivate this channel instead of closing it

### CODE REVIEW

**Comment by benthecarman** [comment]
yeah we had this happen to a few users, i guess our high priority fee rate was between 1-2 sats/vbyte. We since updated it to be a 1 block target instead of 3. But would be nice to be able to just jack this number up so we know this won't happen
image

**Comment by TonyGiorgio** [comment]
Still happening too unfortunately. Bitcoin core has very terrible fee rate estimates that don't reflect reality. 

Does LDK use the high priority rate for anything else? I guess we're going to have to either fix CLN or crank up the range that LDK will allow. It's not acceptable to have massive force closures amongst all of our users whenever fee rates temporarily have a disagreement. That should be another issue in itself.

**Comment by benthecarman** [comment]
For added context, we're using mempool.space's fastest fee target for our High Priority and we had a user get this error this morning

`Channel closed because of an exception: Peer's feerate much too high. Actual: 11001. Expected upper limit: 6250`

**Comment by benthecarman** [comment]
> This PR isn't actually allowing you to configure anything yet though? 

You can just overwrite the function when you implement the trait, the current implementation will just be the default if the user doesn't implement it.

**Comment by benthecarman** [comment]
> An alternative would be to expose a config option

Then we can't have it changing on the mempool, would just be a hard coded value.

**Comment by benthecarman** [comment]
> We could do a multiplier on the queried `HighPriority` fee rate?

That could work

**Comment by benthecarman** [comment]
Changed to be a part of `ChannelConfig` not sure if I handled the serialization correctly however

**Comment by benthecarman** [comment]
Closing in favor of #2660

**Pull request closed without merging**
