### PR TITLE
Log as channel liquidities are/not updated in ProbabilisticScorer

### PR DESCRIPTION
**Pull request by TheBlueMatt**
Does what it says on the tin. Not a whole lot more, getting visibility into the liquidities assigned in the scorer may be useful to debug stuff in the field if anything goes wrong.

### CODE REVIEW

**Comment by TheBlueMatt** [comment]
I ran into https://github.com/ElementsProject/lightning/issues/5154 which caused me to keep retrying a payment across the same first hop over and over again, as we were trusting our own local state over any scoring data. I still think this is the correct behavior - ultimately my immediate peer is exhibiting a bug and I should close the channel, but the logging was substantially lacking, which is improved here.

**Comment by TheBlueMatt** [comment]
Rebased.

**Comment by TheBlueMatt** [comment]
CC https://github.com/lightning/bolts/pull/979

**Review by valentinewallace — APPROVED** [review]
LGTM

**Review by vincenzopalazzo — APPROVED** [review]
LGTM!

**Comment by TheBlueMatt** [comment]
Dropped the log commit as we should actually fix it per #1450 instead of just changing logging.

**Review by arik-so — APPROVED** [review]

**Review by valentinewallace — APPROVED** [review]

**Pull request merged**
