### PR TITLE
Extract peer message handling into separate method.

### PR DESCRIPTION
**Pull request by arik-so**
Additionally, convert some handling macros into a method to avoid hidden control flow logic affecting a "parent" scope.

### CODE REVIEW

**Comment by jkczyz** [comment]
Concept ACK. Nice refactor!

I'd like to see the PR broken into smaller commits. Possibly:
- Refactor `encode_and_send_msg!` macro as `enqueue_message` method
- Refactor `try_potential_handleerror!` macro as `process_lightning_error` method
- Refactor message handling out from `do_read_event`

**Comment by ariard** [comment]
@arik-so Do you see this as a first step toward custom message passing ? Like adding a trait to PeerHandler, `MessageExtensionProxy::handle_unknown_message -> MessageProcessingDecision` ?

I agree with Jeff, splitting in smaller commits would be better.

**Comment by arik-so** [comment]
I do indeed see it as a first step towards that. I'm currently focusing on some refactors for the modular handshake PR, and will break this one down into smaller pieces after. 

One of the challenges of breaking this into smaller pieces is that the extraction of message handling into a separate method requires a redeclaration of the macros. But converting the macros into methods doesn't convey the necessity of doing so for the sake of refactoring.

**Comment by arik-so** [comment]
MessageProcessingDecision could also be something much more involved in the medium term future, as there should be a way for non-C-languages to pass in lambdas for handling custom inputs. That in itself presents some challenges due to various environments' issues with C lambdas capturing context, but that's merely a side note here.

**Comment by TheBlueMatt** [comment]
Before we go too far down this rabbit hole, it would be nice to get a fix for the relay of graph messages, ala https://github.com/TheBlueMatt/rust-lightning/commit/2ce646f575b2f81e4f0f56a4ca0f11551866279e. I'm worried that this direction is going to make it harder to do eventually and we may have to walk things back, so would be nice to get that incorporated.

**Comment by TheBlueMatt** [comment]
This kinda happened in part on accident with the custom message work, and the rest is more actively maintained in #1023. Closing this here as superseded.

**Pull request closed without merging**
