### PR TITLE
Rename NetAddress::Tcp types

### LINKED ISSUE #2358: Modify NetAddress Enum naming
IPv4 socket addresses consist of an [IPv4 address](https://doc.rust-lang.org/stable/std/net/struct.Ipv4Addr.html) and a 16-bit port number, as stated in [IETF RFC 793](https://tools.ietf.org/html/rfc793)

It may be good to use `SocketV4` and `SocketV6` here, and also the same naming in Rust std [SocketAddr](https://doc.rust-lang.org/stable/std/net/enum.SocketAddr.html)

https://github.com/lightningdevkit/rust-lightning/blob/74a9ed9c1978da15ca49b64fc81e01bbcb3f6ae1/lightning/src/ln/msgs.rs#L745-L759

If this proposal is good, I am happy to do this and also #2183, #2156 at the same time.  Some these are implemented in our project.
https://github.com/kuutamolabs/lightning-knd/blob/e5f05755be1c702c56b469964c7d9586bce15e5d/api/src/lib.rs

### PR DESCRIPTION
**Pull request by yanganto**
fix #2358

### CODE REVIEW

**Review by adoerr — COMMENTED** [review]
NACK

I find this quite confusing. If we are interested in the protocol which is used in conjunction with and IP address we should rather add an additional `protocol` struct field to the `IPv4` and `IPv6` enum item struct fields.

That being said, I couldn't find any use of `NetAddress::IPv4` or `NetAddress::IPv6` were a distinction wrt `TCP` or `UDP` is being made.

**Comment by yanganto** [comment]
> That being said, I couldn't find any use of `NetAddress::IPv4` or `NetAddress::IPv6` were a distinction wrt `TCP` or `UDP` is being made.

Will `SocketAddrV4` and `SocketAddrV6` be much better?  These are the original proposal in the issue. #2358 
https://doc.rust-lang.org/stable/std/net/struct.SocketAddrV4.html

**Comment by adoerr** [comment]
> > That being said, I couldn't find any use of `NetAddress::IPv4` or `NetAddress::IPv6` were a distinction wrt `TCP` or `UDP` is being made.
> 
> Will `SocketAddrV4` and `SocketAddrV6` be much better? These are the original proposal in the issue. #2358 https://doc.rust-lang.org/stable/std/net/struct.SocketAddrV4.html

At least this would be less confusing, IMO.

Given the original proposal comments, I personally don't see a pressing need to change the current naming, though.

**Review by dunxen — DISMISSED** [review]
It's more precise naming, but less common in terms of what users generally see and I don't feel like it necessarily clarifies things, but I'm not in any way opposed to renaming. Precise is nice.

**Comment by valentinewallace** [comment]
I honestly think this naming is more confusing and we should just update the docs to specify TCP.

**Comment by yanganto** [comment]
> I honestly think this naming is more confusing and we should just update the docs to specify TCP.

Will `TcpV4SockAddr` looks good for you?

**Comment by dunxen** [comment]
Since I don’t think we have complete agreement on what we’d want to rename it to, and that it’s not currently confusing, I suggest just renaming if/when it would be confusing and leaving it for now.

**Comment by valentinewallace** [comment]
I think we'll pass on this one for reasons stated above but appreciate your contribution to the project 🙏

**Comment by yanganto** [comment]
Ah... @valentinewallace  It is confusing, and really weird compared with Rust standard lib net types.  I believe you just used the wrong naming for a while and then get used to it.  Anyone using Rust programming on the network and for the first time using this crate will see this is confusing.

Here are the net types in Rust.  (By definition `socket = Ip + port`, and you mess up this) 
https://doc.rust-lang.org/stable/std/net/enum.SocketAddr.html

```rust
use std::net::{IpAddr, Ipv4Addr, SocketAddr};
let socket = SocketAddr::new(IpAddr::V4(Ipv4Addr::new(127, 0, 0, 1)), 8080);
```

As you can see, the `SocketAddr`(`SocketV4Addr` and `SocketV6Addr`) here are the same with `NetAddress::IPV4`.

You can make an `Into` trait and you will see how confusing it will be.

```rust
use std::net::{IpAddr, Ipv4Addr, SocketAddr};
use lightning::ln::msgs::NetAddress;

let ipv4 = IpAddr::V4(Ipv4Addr::new(127, 0, 0, 1));
let socket = SocketAddr::new(ipv4.clone(), 8080);

// let ipv4_address: NetAddress = ipv4.into();  // This is impossible, because port absent
let ipv4_address: NetAddress = socket.into();
```

That is the reason I suggest to use `[SocketAddrV4](https://doc.rust-lang.org/stable/std/net/struct.SocketAddrV4.html)` and [SocketAddrV6](https://doc.rust-lang.org/stable/std/net/struct.SocketAddrV6.html)

And none of the languages will give an ip address with a port, but here.  And then you say it is not confusing.
- [python](https://docs.python.org/3/howto/ipaddress.html)
- [go](https://pkg.go.dev/net/netip@go1.20.6#Addr) 
- [c#](https://learn.microsoft.com/en-us/dotnet/api/system.net.ipaddress?view=net-7.0)
- [java](https://docs.oracle.com/javase/8/docs/api/java/net/InetAddress.html)

**Pull request closed without merging**
