### PR TITLE
Make timer_tick_occurred a second long timer

### PR DESCRIPTION
**Pull request by shaavan**
This PR updates timer_tick_occurred to operate on a second-long timer, providing finer timing control.

Reasoning:
1. This PR is the prerequisite of #3010, which introduces the ability to retry the InvoiceRequest message in a finite time if we have not received the corresponding BOLT12 Invoice back.
2. The retries need to be faster than a standard minute-long timer.
3. The discussion was between introducing a new counter vs changing timer_tick duration (see [comment](https://github.com/lightningdevkit/rust-lightning/pull/3010#issuecomment-2108708311)). This PR is an attempt at the second approach.

### CODE REVIEW

**Comment by jkczyz** [comment]
> This enhancement enhances the system's flexibility and accuracy in timing operations.

This doesn't really say anything. Please clearly state the practical reason for the change.

**Comment by shaavan** [comment]
Updated from [pr3065.01](https://github.com/shaavan/rust-lightning/commits/pr3065.01) to [pr3065.02](https://github.com/shaavan/rust-lightning/commits/pr3065.02) ([diff](https://github.com/shaavan/rust-lightning/compare/pr3065.01..pr3065.02)):
Addressed @TheBlueMatt comment:

Changes:
1. Introduce a new constant `TICKS_PER_MINUTE` and use it as the multiplying factor for other constants. This will allow us to keep track of the multiplying factor and make maintenance easy, in case we change this later.

@TheBlueMatt 
I think renaming the function to cause an explicit API failure will be a good idea. However, I haven't implemented it yet. Would love to make sure that it is the right move before I move forward with the name change.
Thanks for the discussion, suggestions, and pointers, everyone.

**Comment by jkczyz** [comment]
> It gets called in `PeerManager::do_attempt_write_data`, which can happen every time a ping needs to be sent out (currently every 10 secs via `PeerManager::timer_tick_occurred`), and on every call to `PeerManager::process_events` and `PeerManager::write_buffer_space_avail`. So, it may actually get called too often, but some simple rate limiting per retry request in `release_pending_messages` would help.

Yeah... though I'm not sure how we'd do that rate limiting. Would an exponential backoff be fine? Also note that `OffersMessageHandler::release_pending_messages` is called each time `next_onion_message_for_peer` is called. So if you have a lot of peers, it will be called more frequently than if you have few. I guess `ChannelManager` knows how many peers it has, so it could take that into account?

We also may want to consider using different reply paths on retries (and maybe the initial sends for that matter) in case the reply path used is the issue.

**Comment by shaavan** [comment]
I've updated #3010 with the new approach (see [comment](https://github.com/lightningdevkit/rust-lightning/pull/3010#issuecomment-2158324567)).

Since we no longer need a sub-minute timer with this new method, this PR has become redundant. So, I'll go ahead and close it. Thanks a lot, everyone, for all the pointers and discussions!

**Pull request closed without merging**
