### PR TITLE
Require `chain::Listen` impls in block sync be `Send + Sync`

### PR DESCRIPTION
**Pull request by TheBlueMatt**
Users who want to use `lightning-block-sync`'s `init` module would
be reasonable in wanting to use it in a multithreaded environment,
however because it takes a list of listeners as `dyn chain::Listen`
without any `Send` or `Sync` bound they fail in doing so.

Here we add a `Send + Sync` bound, requiring any listeners be both.
This could be less generic for users with their own `chain::Listen`
listener that is *not* `Send` or `Sync`, but given multi-threading
support is important and the LDK-included `chain::Listen`
implementations are `Send + Sync`, this seems like an acceptable
tradeoff.

CC @johncantrell97

### CODE REVIEW

**Comment by TheBlueMatt** [comment]
Tagging 106 as it addresses a user issue.

**Comment by Kixunil** [comment]
Note that it seems to be possible to allow both `Send + Sync` and non-`Send + Sync`. Disclaimer: randomly noticed; only saw part of the code, I may be missing something.

```rust
// this blanket impl is backwards-incompatible but shouldn't be a huge issue for implementors
// it'll probably remove their code if it causes failure and DynamicWrapper shouldn't be needed any longer
impl<T: Listen + ?Sized> Listen for &T {
    fn block_connected(&self, block: &Block, height: u32) {
        (*self).block_connected(block, height)
    }
    fn block_disconnected(&self, header: &BlockHeader, height: u32) {
        (*self).block_disconnected(header, height)
    }
}

struct ChainListenerSet<T: Listen>(Vec<(u32, T)>);
```

The users can then pick whatever is the most suitable for them. `Mock` could just be `Send + Sync` or just have two mocks.

**Comment by TheBlueMatt** [comment]
Yea, removing the dyn would fix it, but sadly this API is intended to be used with at least two different types of Listen in the same Vec, hence the dyn :/

**Comment by Kixunil** [comment]
@TheBlueMatt you can still pass in `Vec<&dyn Listen>` or `Vec<&(dyn Listen + Send + Sync)>` depending on what's needed, that's the point. It only requires* the blanket impl above, which is backwards-incompatible with very little annoyance.

*Not strictly required, you could also write `T: Listen + ?Sized` bound and `Vec<&T>` but I find it messy. OTOH it'd enable use of default argument which could be nice if most people use `dyn Listen + Send + Sync`

**Comment by TheBlueMatt** [comment]
Oh! I see your point - `&dyn Listen` implements `Listen + ?Sized` so we can make it generic anyway, good point, indeed, can do that!

**Comment by TheBlueMatt** [comment]
Note that you have to use `&T` because of the `?Sized` - we don't know the size so we can't instantiate a Vec of the objects.

**Comment by Kixunil** [comment]
`&dyn Listen` only implements `Listen` with the blanket impl. But `dyn Listen` does so if you force reference you can avoid blanket impl.

**Review by arik-so — APPROVED** [review]

**Review by jkczyz — APPROVED** [review]

**Pull request merged**
