### PR TITLE
[WIP] New ChannelId type, wrapper for [u8; 32]

### PR DESCRIPTION
**Pull request by optout21**
Partial solution for #2408 .

### CODE REVIEW

**Comment by ariard** [comment]
"A unique 32-byte identifier for a channel.”

I think the uniqueness derivation guarantees can be documented (both for legacy channels and new channel id dual funding). Our internal `ChannelId` struct could be added a per-context (legacy/ dual-funding) prefix to commit to the channel type, and this prefix could be consumed by something like the Validating Lightning Signer to enforce channel policy based on the type. As a practical application, I think this is a bit of a premature though policy downgrade based on channel type confusion has been a real security issue for VLS in the past.

**Comment by optout21** [comment]
Checks OK except per-commit check; squashing the commits would probably solve it.
Not intended for merging in this form, closing.

**Comment by optout21** [comment]
> I think the uniqueness derivation guarantees can be documented

I haven't given much though about the exact meaning of uniqueness here, is it for the whole network, for one node, or for one node-pair.

> Our internal `ChannelId` struct could be added a per-context (legacy/ dual-funding) prefix to commit to the channel type

I was thinking the same, but then I realized that this does not make much sense, as often the channel ID is received from the network in messages, and no context information is available there. This could be done only with a change in the protocol...
In general most of the time it's not possible to know if a channel ID is temporary or funding-based, so I decided that storing this info in the few cases when it is known does not make much sense.

(BTW, latest non-draft PR is #2485 )

**Comment by optout21** [comment]
An example: we receive a `closing_signed` message. It contains a channel ID, which is deserialized into a field of ChannelId type. At this point we don't even know if the channel exists. Then we look up this channel, and check if it's in the right state. Could it be a temporary channel ID? Maybe in this particular case it cannot, but I imagine there are scenarios where both are possible.
The point is that that variety of the channel ID is often can be inferred from external context, and it may be messy to try to capture this in an enum. Or it's possible to have a generic/unknown value of the enum, but that makes the whole point weaker.

**Pull request closed without merging**
